/**
 * @packageDocumentation
 * @module XToken Constants
 */

// Contracts
export const AAVE = 'aave'
export const AAVE_GOVERNANCE_V2 = 'aaveGovernanceV2'
export const ALPHA = 'alpha'
export const BALANCER_V2_VAULT = 'balancerV2Vault'
export const BANCOR_CONTRACT_REGISTRY = 'bancorContractRegistry'
export const BNT = 'bnt'
export const BUSD = 'busd'
export const DAI = 'dai'
export const DMM_FACTORY = 'dmmFactory'
export const ETH = 'eth'
export const ETH_BNT_ANCHOR = 'ethBntAnchor'
export const ETH_RSI_60_40 = 'ethrsi6040'
export const EXCHANGE_RATES = 'exchangeRates'
export const FEE_POOL = 'feePool'
export const FRAX = 'frax'
export const INCH = 'inch'
export const INCH_LIQUIDITY_PROTOCOL = '1InchLiquidityProtocol'
export const KNC = 'knc'
export const KYBER_GOVERNANCE = 'kyberGovernance'
export const KYBER_PROXY = 'kyberProxy'
export const PROXY_ADMIN = 'proxyAdmin'
export const REVENUE_CONTROLLER = 'revenueController'
export const REWARD_CONTROLLER = 'rewardController'
export const REN_BTC = 'renBTC'
export const SNX = 'snx'
export const S_ETH = 'sETH'
export const S_USD = 'sUSD'
export const SYNTHETIX_ADDRESS_RESOLVER = 'synthetixAddressResolver'
export const TRADE_ACCOUNTING = 'tradeAccounting'
export const UNISWAP_LIBRARY = 'uniswapLibrary'
export const UNISWAP_V2_PAIR = 'uniswapV2Pair'
export const USDC = 'usdc'
export const USDT = 'usdt'
export const UST = 'ust'
export const WBTC = 'wbtc'
export const WETH = 'weth'
export const X_ALPHA_A = 'xALPHAa'
export const X_AAVE_A = 'xAAVEa'
export const X_AAVE_B = 'xAAVEb'
export const X_BNT_A = 'xBNTa'
export const X_BNT_A_BANCOR_POOL = 'xbntaBancorPool'
export const X_BNT_A_MERKLE_CLAIM = 'xBNTaMerkleClaim'
export const X_INCH_A = 'xINCHa'
export const X_INCH_B = 'xINCHb'
export const X_KNC_A = 'xKNCa'
export const X_KNC_B = 'xKNCb'
export const X_KNC_A_KYBER_POOL = 'xkncaKyberPool'
export const X_KNC_A_UNISWAP_POOL = 'xkncaUniswapPool'
export const X_KNC_B_UNISWAP_POOL = 'xkncbUniswapPool'
export const X_SNX_A = 'xSNXa'
export const X_SNX_ADMIN = 'xSNXAdmin'
export const X_SNX_A_MERKLE_CLAIM = 'xSNXaMerkleClaim'
export const X_AAVE_A_BALANCER_POOL = 'xaaveaBalancerPool'
export const X_AAVE_B_BALANCER_POOL = 'xaavebBalancerPool'
export const X_INCH_A_INCH_POOL = 'xinchaInchPool'
export const X_INCH_B_INCH_POOL = 'xinchbInchPool'
export const X_SNX_A_BALANCER_POOL = 'xsnxaBalancerPool'
export const X_SNX_A_BALANCER_POOL_V2 = 'xsnxaBalancerPoolV2'
export const XTK_MANAGEMENT_STAKING_MODULE = 'xtkManagementStakingModule'
export const XTOKEN_MANAGER = 'xTokenManager'
export const X_U3LP_A = 'xU3LPa'
export const X_U3LP_B = 'xU3LPb'
export const X_U3LP_C = 'xU3LPc'
export const X_U3LP_D = 'xU3LPd'
export const X_U3LP_E = 'xU3LPe'
export const X_U3LP_F = 'xU3LPf'
export const X_U3LP_G = 'xU3LPg'
export const X_U3LP_H = 'xU3LPh'

// Trade types
export const BUY = 'buy'
export const SELL = 'sell'
