/**
 * @packageDocumentation
 * @module XToken Constants
 */

// Contracts
export const AAVE = 'aave'
export const AAVE_GOVERNANCE_V2 = 'aaveGovernanceV2'
export const BANCOR_CONTRACT_REGISTRY = 'bancorContractRegistry'
export const BNT = 'bnt'
export const ETH = 'eth'
export const ETH_BNT_ANCHOR = 'ethBntAnchor'
export const ETH_RSI_60_40 = 'ethrsi6040'
export const EXCHANGE_RATES = 'exchangeRates'
export const FEE_POOL = 'feePool'
export const INCH = 'inch'
export const INCH_LIQUIDITY_PROTOCOL = '1InchLiquidityProtocol'
export const KNC = 'knc'
export const KYBER_GOVERNANCE = 'kyberGovernance'
export const KYBER_PROXY = 'kyberProxy'
export const SNX = 'snx'
export const SYNTHETIX_ADDRESS_RESOLVER = 'synthetixAddressResolver'
export const TRADE_ACCOUNTING = 'tradeAccounting'
export const UNISWAP_V2_PAIR = 'uniswapV2Pair'
export const USDC = 'usdc'
export const WETH = 'weth'
export const X_AAVE_A = 'xAAVEa'
export const X_AAVE_B = 'xAAVEb'
export const X_BNT_A = 'xBNTa'
export const X_BNT_A_BANCOR_POOL = 'xbntaBancorPool'
export const X_INCH_A = 'xINCHa'
export const X_INCH_B = 'xINCHb'
export const X_KNC_A = 'xKNCa'
export const X_KNC_B = 'xKNCb'
export const X_KNC_A_UNISWAP_POOL = 'xkncaUniswapPool'
export const X_KNC_B_UNISWAP_POOL = 'xkncbUniswapPool'
export const X_SNX_A = 'xSNXa'
export const X_SNX_A_ADMIN = 'xSNXaAdmin'
export const X_AAVE_A_BALANCER_POOL = 'xaaveaBalancerPool'
export const X_AAVE_B_BALANCER_POOL = 'xaavebBalancerPool'
export const X_INCH_A_INCH_POOL = 'xinchaInchPool'
export const X_INCH_B_INCH_POOL = 'xinchbInchPool'
export const X_SNX_A_BALANCER_POOL = 'xsnxaBalancerPool'

// Trade types
export const BUY = 'buy'
export const SELL = 'sell'
